# Generated by Django 2.2.6 on 2020-05-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200511_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
