# Generated by Django 2.2.6 on 2020-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='order',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
