# Generated by Django 2.2.10 on 2020-05-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200513_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='', max_length=512, verbose_name='Описание теста'),
            preserve_default=False,
        ),
    ]
