# Generated by Django 2.2.10 on 2020-05-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(max_length=512, verbose_name='Описание теста'),
        ),
    ]
