# Generated by Django 2.2.10 on 2020-05-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200516_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'id')},
        ),
    ]
